[package]
name = "winreg"
edition = "2021"
rust-version = "1.60"
version = "0.55.0"
authors = ["Igor Shaula <gentoo90@gmail.com>"]
license = "MIT"
description = "Rust bindings to MS Windows Registry API"
repository = "https://github.com/gentoo90/winreg-rs"
documentation = "https://docs.rs/winreg"
readme = "README.md"
keywords = ["Windows", "WinSDK", "Registry"]
categories = ["api-bindings", "os::windows-apis"]

[dependencies]
cfg-if = "1.0"
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_System_Time",
    "Win32_System_Registry",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Diagnostics_Debug",
] }
chrono = { version = "0.4.6", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
rand = "0.3"
tempfile = "~3.0"
serde-transcode = "1"
serde_bytes = "0.11"
